services:
  alicdt-manager:
    image: ${IMAGE_NAME:-ghcr.io/lillinlin/alicdt-manager:latest}
    container_name: alicdt-manager
    restart: always
    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:${PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
